version: "3.8"

services:
  instant-ngp:
    image: cjinone/instantngp-realsense:latest
    stdin_open: true
    tty: true
    environment:
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      DISPLAY: $DISPLAY
    volumes:
      - ../:/volume
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /volume
    privileged: true
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]